DROP DATABASE IF EXISTS FMU_DB;
CREATE DATABASE FMU_DB;
USE FMU_DB;

DROP TABLE IF EXISTS CONSULT, CONSULT_CATEGORIES, REQUEST_FOR_CONSULT, PAYMENT, REVIEW, MESSAGE, USER, CONSULT_IMAGE, REVIEW_IMAGE;

CREATE TABLE USER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(10) NOT NULL,
    GENDER VARCHAR(10),
    AGE INT,
    NICKNAME VARCHAR(50) NOT NULL UNIQUE,
    PROFILE_IMG VARCHAR(100),
    CREDIT INT DEFAULT 0,
    PLATFORM VARCHAR(30),
    API_ID VARCHAR(100),
    
    NAME VARCHAR(10),
    BELONG VARCHAR(30),
    OCCUPATION VARCHAR(30),
    PHONE VARCHAR(30) UNIQUE
);

CREATE TABLE CONSULT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STYLIST_ID INT,
    USER_ID INT,
    CATEGORY VARCHAR(20),
    GENDER VARCHAR(10),
    TOP VARCHAR(100),
    BOTTOM VARCHAR(100),
    HEIGHT INT,
    WEIGHT INT,
    PRICE INT,
    CONTENTS VARCHAR(100),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATE VARCHAR(100),

	CONSTRAINT FOREIGN KEY (STYLIST_ID) REFERENCES USER(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE CONSULT_IMAGE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONSULT_ID INT,
    IMAGE_PATH VARCHAR(50),

    CONSTRAINT FOREIGN KEY (CONSULT_ID) REFERENCES CONSULT(ID) ON DELETE CASCADE
);

CREATE TABLE CONSULT_CATEGORIES(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CONSULT_ID INT,
    CATEGORY VARCHAR(50),
    
    CONSTRAINT FOREIGN KEY (CONSULT_ID) REFERENCES CONSULT(ID) ON DELETE CASCADE
);

CREATE TABLE REQUEST_FOR_CONSULT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    STYLIST_ID INT,
    CONSULT_ID INT,
    STATE VARCHAR(100) DEFAULT "REQUESTED",
    # REQUESTED, ACCEPTED, DENIED
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FOREIGN KEY (STYLIST_ID) REFERENCES USER(ID) ON DELETE CASCADE,
    CONSTRAINT FOREIGN KEY (CONSULT_ID) REFERENCES CONSULT(ID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SOURCE INT,
    TARGET INT,
    AMOUNT INT,
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT FOREIGN KEY (SOURCE) REFERENCES USER(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (TARGET) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SOURCE INT,
    TARGET INT,
    CONTENTS VARCHAR(1000),
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SCORE DOUBLE,

	CONSTRAINT FOREIGN KEY (SOURCE) REFERENCES USER(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (TARGET) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE MESSAGE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SOURCE INT,
    TARGET INT,
    CONTENTS VARCHAR(200),
    REG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    READED BOOLEAN,

	CONSTRAINT FOREIGN KEY (SOURCE) REFERENCES USER(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (TARGET) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW_IMAGE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    REVIEW_ID INT,
    IMAGE_PATH VARCHAR(50),
    
    CONSTRAINT FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(ID) ON DELETE CASCADE
);

SHOW TABLES;